"""
Default Values and Constants

Centralized location for all default values used throughout the package.
"""

# === Extraction Defaults ===

DEFAULT_EXTRACTION_CONCURRENCY = 10
DEFAULT_EMBEDDING_CONCURRENCY = 5
DEFAULT_EMBEDDING_BATCH_SIZE = 100
DEFAULT_DEDUP_CONCURRENCY = 10

# === Deduplication Defaults ===

DEFAULT_DEDUP_SIMILARITY_THRESHOLD = 0.70  # Wide net for clustering
DEFAULT_DEDUP_BATCH_SIZE = 15  # Entities per LLM verification call

# === Query Defaults ===

DEFAULT_ENTITY_THRESHOLD = 0.35
DEFAULT_TOPIC_THRESHOLD = 0.35
DEFAULT_RELEVANCE_THRESHOLD = 0.45  # High vs low relevance split
DEFAULT_GLOBAL_SEARCH_THRESHOLD = 0.25

DEFAULT_MAX_CHUNKS = 30
DEFAULT_MAX_FACTS = 40
DEFAULT_MAX_TOPIC_CHUNKS = 15
DEFAULT_MAX_LOW_RELEVANCE_CHUNKS = 20
DEFAULT_MAX_NEIGHBORS = 10
DEFAULT_MAX_SUBQUERIES = 5
DEFAULT_MAX_CONCURRENT_SUBQUERIES = 5

# === Storage Defaults ===

DEFAULT_PARQUET_COMPRESSION = "zstd"
DEFAULT_LANCEDB_INDEX_TYPE = "IVF_PQ"
DEFAULT_WRITE_BATCH_SIZE = 250

# === Embedding Defaults ===

DEFAULT_EMBEDDING_MODEL = "text-embedding-3-large"
DEFAULT_EMBEDDING_DIMENSIONS = 3072

# === Chunking Defaults ===

DEFAULT_MIN_CHUNK_LENGTH = 50
DEFAULT_PDF_MAX_TOKENS = 100000
DEFAULT_PDF_TEMPERATURE = 0.1
